### ISSUE TITLE
How to unlock

### ISSUE THREAD

**Issue by anthonywebb** [vincentbernat/dashkiosk-android#1]
Clicking around the options menu I accidentially hit the "lock" option, and now I cant get back into the settings to fix.  Is there a way to "unlock"?

**Comment by vincentbernat** [comment]
You can use adb. The preferences are stored in `/data/data/com.deezer.android.dashkiosk`. You can either delete the file or edit it. I don't remember if it's an XML file or a database. If it's a database, you can use sqlite to poke in it.

Alternatively, you can use `pm clear com.deezer.android.dashkiosk` (still from `adb shell`).

**Comment by vincentbernat** [comment]
Not much else to do. I suppose this did the trick. Closing the issue.
